version: '3.8'

services:
  ai_worker:
    build:
      context: .
      dockerfile: services/messages/Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - appwrite

  payment_service:
    build:
      context: .
      dockerfile: services/payments/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
